# -*- coding: utf-8 -*-
"""Python_IFeELSE

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lvBcPmzXfk_l8-7dQJXwm7XvNh4Xznus
"""

#EX1

numero1 = int(input("Digite o primeiro numero: "))
numero2  = int(input("Digite o segundo numero: "))

soma = numero1 + numero2

if soma > 15:
  print("E maior")
else:
  print("E menor")

#print(f"A soma e {validade}")

#EX2

valor = int(input("Digite o valor inteiro: "))

#situacao = (valor >= 0)

if valor >= 0:
  print("Ta ok")
else:
  print("Nao ta ok")

#EX3

idade = int(input("Digite sua idade: "))

if idade >= 18:
  print("Pode ser preso")
else:
  print("Ainda e crianca")

#EX4

temp_ideal = float(input("Qual a sua temperatura ideal: "))
temp_atual = float(input("Qual a temperatura agora: "))

temp_min = temp_ideal - 5
temp_max = temp_ideal + 5

if temp_min <= temp_atual <= temp_max:
  print("Esta agradavel")
else:
  print("Nao esta agradavel")

#EX5

numero1 = float(input("Insira o primeiro numero: "))
numero2 = float(input("Insira o segundo numero: "))

if numero1 == numero2:
  print("Igual")
else:
  print("Diferentes")

#EX6

senha_digitada = float(input("Insira a senha: "))

if senha_digitada == 1234:
  print("ACESSO PERMITIDO")
else:
  print("ACESSO NEGADO")

#EX7

nota1 = float(input("Insira a primeira nota: "))
nota2 = float(input("Insira a segunda nota: "))
media = (nota1 + nota2) / 2

if media >= 7:
  print("APROVADO")
elif media >=7 and 5:
  print("EXAME")
else:
  print("REPROVADO")

#Nao esta aparecendo o "exame"

#EX8
time_1 = str(input("Qual o primeiro time? ")).upper()
time_2 = str(input("Qual o segundo time? ")).upper()
placar_1 = int(input(f"Quantos gols o {time_1} fez: "))
placar_2 = int(input(f"Quantos gols o {time_2} fez: "))

if vitoria_1 := placar_1 > placar_2:
    print(f"Ai sim! Vitoria do {time_1} de {placar_1} x {placar_2}")
elif vitoria_2 := placar_2 > placar_1:
    print(f"Ai sim! Vitoria do {time_2} de {placar_2} x {placar_1}")
else:
  print("Empate hein, vencemos na proxima")

#EX9

print("Ola caro aluno! Por favor, informe seu horario de aula")

print("M-Matutino")
print("V-Vespertino")
print("N-Noturno")

horario_aula = str(input()).upper()

if horario_aula == "M":
  print("Bom dia! Vamos iniciar o programa de aulas de hoje")
elif horario_aula == "V":
  print("Boa tarde! Vamos iniciar o programa de aulas de hoje")
elif horario_aula == "N":
  print("Boa noite! Vamos iniciar o programa de aulas de hoje")

#EX10

idade = int(input("Insira a idade do paciente: "))

if idade <= 11:
  print("O paciente em questao e crianca")
elif 12 <= idade < 18:
  print("O paciente em questao e adolescente")
elif 18 <= idade <= 24:
  print("O paciente em questao e jovem")
elif 25 <= idade <= 40:
  print("O paciente em questao e adulto")
elif 41 <= idade <= 60:
  print("O paciente em questao esta meio velho")
elif 60 < idade:
  print("O paciente em questao ta velho")

#EX11

salario = float(input("Insira o salario do colaborador: "))

if salario <= 200:
  print("Salario atual:",salario,"\n","Aumento de 20%","\n","Aumento real:" ,(salario * 20)/100,"\n", "Novo salario:",(salario * 20)/100 + salario)
elif 280 <= salario <= 700:
  print("Salario atual:",salario,"\n","Aumento de 15%","\n","Aumento real:" ,(salario * 15)/100,"\n", "Novo salario:",(salario * 15)/100 + salario)
elif 700 <= salario <= 1500:
  print("Salario atual:",salario,"\n","Aumento de 10%","\n","Aumento real:" ,(salario * 10)/100,"\n", "Novo salario:",(salario * 10)/100 + salario)
elif salario >= 1500:
  print("Salario atual:",salario,"\n","Aumento de 5%","\n","Aumento real:" ,(salario * 5)/100,"\n", "Novo salario:",(salario * 5)/100 + salario)

#EX12

numero = int(input("Insira um número de 1 a 7: "))

if numero == 1:
    print("Domingo")
elif numero == 2:
    print("Segunda-feira")
elif numero == 3:
    print("Terça-feira")
elif numero == 4:
    print("Quarta-feira")
elif numero == 5:
    print("Quinta-feira")
elif numero == 6:
    print("Sexta-feira")
elif numero == 7:
    print("Sábado")
else:
    print("Número inválido. Insira um número de 1 a 7.")

#EX13

print("Bem vindo para o conversor de escalas, para começar Insira a escala termométrica utilizada: ")
print("(F) Fahrenheit")
print("(C) Celsius")

while True:
    temp_usado = input().upper()
    if temp_usado in ["F", "C"]:
        break
    else:
        print("Entrada inválida. Por favor, insira 'F' para Fahrenheit ou 'C' para Celsius.")

graus = float(input("Insira a temperatura atual: "))

if temp_usado == "C":
  print(graus * 1.8 + 32, "Fahrenheit")
elif temp_usado == "F":
  print((graus - 32) / 1.8, "Celsius")

#EX14

idade = int(input("Insira a data do usuario: "))

if idade < 16:
  print("Proibido")
elif 16 <= idade > 18:
  print("Optativo")
elif 18 == idade < 65:
  print("Obrigatorio")
elif 65 <= idade:
  print("Optativo")

#EX15

print("Responda as perguntas apenas com sim ou nao")

pergunta1 = input("Telefonou para a vitima? ").lower()
pergunta2 = input("Esteve no local do crime? ").lower()
pergunta3 = input("Mora perto da vitima? ").lower()
pergunta4 = input("Devia para a vitima? ").lower()
pergunta5 = input("Ja trabalhou para a vitima? ").lower()

positivas = 0

if pergunta1 == "sim":
  positivas += 1
elif pergunta2 == "sim":
  positivas += 2
elif pergunta3 == "sim":
  positivas += 1
elif pergunta4 == "sim":
  positivas += 2
elif pergunta5 == "sim":
  positivas += 1

if 2 == positivas:
  print("Suspeita")
elif 3 <= positivas <= 4:
  print("Cumplice")
elif 5 <= positivas:
  print("Assassino")
else:
  if 1 >= positivas:
    print("Inocente")

#EX17

produto1 = float(input("Insira o e valor do primeiro produto: R$"))
produto2 = float(input("Insira o valor do segundo produto: R$"))
produto3 = float(input("Insira o valor do terceiro produto: R$"))

if produto1 < produto2 and produto1 < produto3:
  print("O produto 1 e o mais barato")
elif produto2 < produto1 and produto2 < produto3:
  print("O produto 2 e o mais barato")
elif produto3 < produto1 and produto3 < produto2:
  print("O produto 3 e o mais barato")
else:
  print("Os produtos possuem o mesmo valor")